### ISSUE TITLE
Make errors more informative

### ISSUE THREAD

**Issue by adriank** [mileszim/twat#4]
Hello,

I encountered an error that says just:

error http 401

I found out that it was authentication HTTP error with message 'statusMessage': 'Authorization Required'. Would it be possible to add res.statusMessage (and possibly the body of response) in error thrown at the user on line 212 in file stream.js? It could look like:

error http 401 Authorization Required

Thanks in advance!

**Comment by mileszim** [comment]
Go ahead and make PR with how you want it to look and we'll go from there. Thanks!
